In [10]:
# !/usr/bin/env python3 
# executable - set up paths for import
import os
import sys
# to setup import paths add project root dir to sys.path (with baseVR dir in it)
sys.path.append(os.path.join(os.getcwd(), "..", ".."))
from baseVR.base_functionality import init_import_paths
init_import_paths()

from dashsrc.plot_components.plots import plot_unit_fr_stability
from dashsrc.plot_components.plots import plot_EnsambleEncondings
from analytics_processing import analytics
import analytics_processing.analytics_constants as C
from CustomLogger import CustomLogger as Logger
from analytics_processing.modality_loading import session_modality_from_nas
from analytics_processing.sessions_from_nas_parsing import sessionlist_fullfnames_from_args

from dashsrc.plot_components.plots import plot_SessionWaveforms
from dashsrc.plot_components.plots import plot_EnsembleChoiceEncoding
from dashsrc.plot_components.plot_wrappers.data_selection import group_filter_data


output_dir = "/mnt/SpatialSequenceLearning/Simon/fr_stability/"
data = {}
nas_dir = C.device_paths()[0]
Logger().init_logger(None, None, logging_level="INFO")

import plotly.io as pio

In [11]:


animal_ids = [6]
# animal_ids = [10]
session_ids = None
paradigm_ids = [1100]
excl_session_names = ['2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min', '2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min', '2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min']
cols = ["session_spike_count", "session_nsamples", "cluster_id", "unit_snr", "unit_Vpp"]
width = 700
height = 700
group_by = None

data['SpikeClusterMetadata'] = analytics.get_analytics('SpikeClusterMetadata', mode='set',
                                                      #  columns = cols,
                                                       paradigm_ids=paradigm_ids,
                                                       animal_ids=animal_ids,
                                                       excl_session_names=excl_session_names,
                                                       session_ids=session_ids)

2026-01-17 10:02:13,851|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 0), compute first, or check for typo
2026-01-17 10:02:13,851|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 0), compute first, or check for typo
2026-01-17 10:02:13,950|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 5), compute first, or check for typo
2026-01-17 10:02:13,950|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 5), compute first, or check for typo
2026-01-17 10:02:14,002|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 8), compute first, or check for typo
2026-01-17 10:02:14,002|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 8), compute first, or check for typo
2026-01-17 10:02:14,438|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 29), compute first, or check for typo
2026-01-17 10:02:14,438|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 29), compute first, or check for typo
2026-01-17 10:02:14,463|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 31), compute first, or check for typo
2026-01-17 10:02:14,463|INFO|2561669|analytics|get_analytics
	Analytic `SpikeClusterMetadata` not does not exist for (1100, 6, 31), compute first, or check for typo
2026-01-17 10:02:14,519|INFO|2561669|analytics|get_analytics
	Returning SpikeClusterMetadata for 26 sessions.
Returning SpikeClusterMetadata for 26 sessions.================================================================================

In [3]:
data['FiringRate40msHz'] = analytics.get_analytics('FiringRate40msHz', mode='set',
                                        #  columns = cols,
                                        paradigm_ids=paradigm_ids,
                                        animal_ids=animal_ids,
                                        excl_session_names=excl_session_names,
                                        session_ids=session_ids)
data['FiringRate40msHz']

2026-01-17 09:52:45,214|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msHz` not does not exist for (1100, 6, 0), compute first, or check for typo
2026-01-17 09:52:45,347|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msHz` not does not exist for (1100, 6, 5), compute first, or check for typo
2026-01-17 09:52:45,405|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msHz` not does not exist for (1100, 6, 8), compute first, or check for typo
2026-01-17 09:52:46,035|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msHz` not does not exist for (1100, 6, 29), compute first, or check for typo
2026-01-17 09:52:46,107|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msHz` not does not exist for (1100, 6, 31), compute first, or check for typo
2026-01-17 09:52:46,408|INFO|2561669|analytics|get_analytics
	Returning FiringRate40msHz for 26 sessions.

                                           Unit0001  Unit0002  Unit0003  \
paradigm_id animal_id session_id entry_id
1100        6         1          0                0         0         0
                                 1                0         0         0
                                 2                0         0         0
                                 3                0         0         0
                                 4                0         0         0
...                                             ...       ...       ...
                      33         110898           0         0         0
                                 110899           0         0         0
                                 110900           0         0         0
                                 110901           0         0         0
                                 110902           0         0         0

                                           Unit0004  Unit0005  Unit0006  \
paradigm_id animal_id session_id entry_id
1100        6         1          0                0         0         0
                                 1                0         0         0
                                 2                0         0         0
                                 3                0         0         0
                                 4                0         0         0
...                                             ...       ...       ...
                      33         110898           0         0         0
                                 110899           0         0         0
                                 110900           0         0         0
                                 110901           0         0         0
                                 110902           0         0         0

                                           Unit0007  Unit0008  Unit0009  \
paradigm_id animal_id session_id entry_id
1100        6         1          0                0         0         0
                                 1                0         0         0
                                 2                0         0         0
                                 3                0         0         0
                                 4                0         0         0
...                                             ...       ...       ...
                      33         110898           0         0         0
                                 110899           0         0         0
                                 110900           0         0         0
                                 110901           0         0         0
                                 110902           0         0         0

                                           Unit0010  ...  Unit0070  Unit0071  \
paradigm_id animal_id session_id entry_id            ...
1100        6         1          0                0  ...         0         0
                                 1                0  ...         0         0
                                 2                0  ...         0         0
                                 3                0  ...         0         0
                                 4                0  ...         0         0
...                                             ...  ...       ...       ...
                      33         110898           0  ...         0        25
                                 110899           0  ...         0        25
                                 110900           0  ...         0        25
                                 110901           0  ...         0         0
                                 110902           0  ...        25         0

                                           Unit0072  Unit0073  Unit0074  \
paradigm_id animal_id session_id entry_id
1100        6         1          0                0         0         0
                                 1                0         0         0
                                 2                0         0         0
                                 3                0         0         0
                                 4                0         0         0
...                                             ...       ...       ...
                      33         110898           0         0        50
                                 110899           0         0         0
                                 110900           0         0         0
                                 110901           0         0         0
                                 110902           0         0         0

                                           Unit0075  Unit0076  Unit0077  \
paradigm_id animal_id session_id entry_id
1100        6         1          0                0         0         0
                                 1                0         0         0
                                 2                0         0         0
                                 3                0         0         0
                                 4                0         0         0
...                                             ...       ...       ...
                      33         110898           0         0         0
                                 110899           0         0         0
                                 110900           0         0         0
                                 110901           0         0         0
                                 110902          25         0         0

                                           from_ephys_timestamp  \
paradigm_id animal_id session_id entry_id
1100        6         1          0                            0
                                 1                        40000
                                 2                        80000
                                 3                       120000
                                 4                       160000
...                                                         ...
                      33         110898              4435920000
                                 110899              4435960000
                                 110900              4436000000
                                 110901              4436040000
                                 110902              4436080000

                                           to_ephys_timestamp
paradigm_id animal_id session_id entry_id
1100        6         1          0                      40000
                                 1                      80000
                                 2                     120000
                                 3                     160000
                                 4                     200000
...                                                       ...
                      33         110898            4435960000
                                 110899            4436000000
                                 110900            4436040000
                                 110901            4436080000
                                 110902            4436120000

[1280416 rows x 79 columns]

In [13]:
data['FiringRate40msZ'] = analytics.get_analytics('FiringRate40msZ', mode='set',
                                        #  columns = cols,
                                        paradigm_ids=paradigm_ids,
                                        animal_ids=animal_ids,
                                        excl_session_names=excl_session_names,
                                        session_ids=session_ids)
data['FiringRate40msZ']

2026-01-17 10:02:22,936|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msZ` not does not exist for (1100, 6, 0), compute first, or check for typo
Analytic `FiringRate40msZ` not does not exist for (1100, 6, 0), compute first, or check for typo================================================================================

2026-01-17 10:02:23,063|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msZ` not does not exist for (1100, 6, 5), compute first, or check for typo
Analytic `FiringRate40msZ` not does not exist for (1100, 6, 5), compute first, or check for typo================================================================================

2026-01-17 10:02:23,119|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msZ` not does not exist for (1100, 6, 8), compute first, or check for typo
Analytic `FiringRate40msZ` not does not exist for (1100, 6, 8), compute first, or check for typo================================================================================

2026-01-17 10:02:23,737|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msZ` not does not exist for (1100, 6, 29), compute first, or check for typo
Analytic `FiringRate40msZ` not does not exist for (1100, 6, 29), compute first, or check for typo================================================================================

2026-01-17 10:02:23,808|INFO|2561669|analytics|get_analytics
	Analytic `FiringRate40msZ` not does not exist for (1100, 6, 31), compute first, or check for typo
Analytic `FiringRate40msZ` not does not exist for (1100, 6, 31), compute first, or check for typo================================================================================

2026-01-17 10:02:24,101|INFO|2561669|analytics|get_analytics
	Returning FiringRate40msZ for 26 sessions.
Returning FiringRate40msZ for 26 sessions.================================================================================

                                           Unit0001  Unit0002  Unit0003  \
paradigm_id animal_id session_id entry_id
1100        6         1          0        -0.247117 -0.138099 -0.094517
                                 1        -0.247117 -0.138099 -0.094517
                                 2        -0.247117 -0.138099 -0.094517
                                 3        -0.247117 -0.138099 -0.094517
                                 4        -0.247117 -0.138099 -0.094517
...                                             ...       ...       ...
                      33         110898   -0.125991 -0.386801       NaN
                                 110899   -0.125991 -0.386801       NaN
                                 110900   -0.125991 -0.386801       NaN
                                 110901   -0.125991 -0.386801       NaN
                                 110902   -0.125991 -0.386801       NaN

                                           Unit0004  Unit0005  Unit0006  \
paradigm_id animal_id session_id entry_id
1100        6         1          0        -0.027392 -0.154562       NaN
                                 1        -0.027392 -0.154562       NaN
                                 2        -0.027392 -0.154562       NaN
                                 3        -0.027392 -0.154562       NaN
                                 4        -0.027392 -0.154562       NaN
...                                             ...       ...       ...
                      33         110898   -0.148987 -0.092210 -0.110418
                                 110899   -0.148987 -0.092210 -0.110418
                                 110900   -0.148987 -0.092210 -0.110418
                                 110901   -0.148987 -0.092210 -0.110418
                                 110902   -0.148987 -0.092210 -0.110418

                                           Unit0007  Unit0008  Unit0009  \
paradigm_id animal_id session_id entry_id
1100        6         1          0        -0.042921       NaN  -0.10517
                                 1        -0.042921       NaN  -0.10517
                                 2        -0.042921       NaN  -0.10517
                                 3        -0.042921       NaN  -0.10517
                                 4        -0.042921       NaN  -0.10517
...                                             ...       ...       ...
                      33         110898   -0.543598 -0.223557       NaN
                                 110899   -0.543598 -0.223557       NaN
                                 110900   -0.543598 -0.223557       NaN
                                 110901   -0.543598 -0.223557       NaN
                                 110902   -0.543598 -0.223557       NaN

                                           Unit0010  ...  Unit0070  Unit0071  \
paradigm_id animal_id session_id entry_id            ...
1100        6         1          0        -0.516334  ... -0.220626 -0.349765
                                 1        -0.516334  ... -0.220626 -0.349765
                                 2        -0.516334  ... -0.220626 -0.349765
                                 3        -0.516334  ... -0.220626 -0.349765
                                 4        -0.516334  ... -0.220626 -0.349765
...                                             ...  ...       ...       ...
                      33         110898         NaN  ... -0.350716  0.623731
                                 110899         NaN  ... -0.350716  0.623731
                                 110900         NaN  ... -0.350716  0.623731
                                 110901         NaN  ... -0.350716 -0.815707
                                 110902         NaN  ...  2.588338 -0.815707

                                           Unit0072  Unit0073  Unit0074  \
paradigm_id animal_id session_id entry_id
1100        6         1          0        -0.257008 -0.138511 -0.429521
                                 1        -0.257008 -0.138511 -0.429521
                                 2        -0.257008 -0.138511 -0.429521
                                 3        -0.257008 -0.138511 -0.429521
                                 4        -0.257008 -0.138511 -0.429521
...                                             ...       ...       ...
                      33         110898   -0.235342 -0.121957  1.233482
                                 110899   -0.235342 -0.121957 -1.069864
                                 110900   -0.235342 -0.121957 -1.069864
                                 110901   -0.235342 -0.121957 -1.069864
                                 110902   -0.235342 -0.121957 -1.069864

                                           Unit0075  Unit0076  Unit0077  \
paradigm_id animal_id session_id entry_id
1100        6         1          0        -0.058813 -0.105746 -0.143094
                                 1        -0.058813 -0.105746 -0.143094
                                 2        -0.058813 -0.105746 -0.143094
                                 3        -0.058813 -0.105746 -0.143094
                                 4        -0.058813 -0.105746 -0.143094
...                                             ...       ...       ...
                      33         110898   -0.426348 -0.477327 -0.327046
                                 110899   -0.426348 -0.477327 -0.327046
                                 110900   -0.426348 -0.477327 -0.327046
                                 110901   -0.426348 -0.477327 -0.327046
                                 110902    1.825986 -0.477327 -0.327046

                                           from_ephys_timestamp  \
paradigm_id animal_id session_id entry_id
1100        6         1          0                            0
                                 1                        40000
                                 2                        80000
                                 3                       120000
                                 4                       160000
...                                                         ...
                      33         110898              4435920000
                                 110899              4435960000
                                 110900              4436000000
                                 110901              4436040000
                                 110902              4436080000

                                           to_ephys_timestamp
paradigm_id animal_id session_id entry_id
1100        6         1          0                      40000
                                 1                      80000
                                 2                     120000
                                 3                     160000
                                 4                     200000
...                                                       ...
                      33         110898            4435960000
                                 110899            4436000000
                                 110900            4436040000
                                 110901            4436080000
                                 110902            4436120000

[1280416 rows x 79 columns]

In [4]:
# data['SpikeClusterMetadata'] = data['SpikeClusterMetadata'][data['SpikeClusterMetadata'].cluster_id<21]
data['SpikeClusterMetadata'][['session_spike_count', 'session_nsamples', 'cluster_id']]

                                           session_spike_count  \
paradigm_id animal_id session_id entry_id
1100        6         1          0                        2086
                                 1                         622
                                 2                         291
                                 3                          26
                                 4                         793
...                                                        ...
                      33         72                       1649
                                 73                     103025
                                 74                      20993
                                 75                      24107
                                 76                      11984

                                           session_nsamples  cluster_id
paradigm_id animal_id session_id entry_id
1100        6         1          0                 25759600           1
                                 1                 25759600           2
                                 2                 25759600           3
                                 3                 25759600           4
                                 4                 25759600           5
...                                                     ...         ...
                      33         72                88722000          73
                                 73                88722000          74
                                 74                88722000          75
                                 75                88722000          76
                                 76                88722000          77

[2002 rows x 3 columns]

In [14]:
# fig = plot_unit_fr_stability.render_plot_lineplot(data['SpikeClusterMetadata'])
# fig = plot_unit_fr_stability.render_plot_lineplot(data['FiringRate40msHz'])
fig = plot_unit_fr_stability.render_plot_lineplot(data['FiringRate40msZ'])
# fullfname = f'{output_dir}/unit_fr_stability.svg'
fullfname = f'{output_dir}unit_fr_drift_Z_spikemetadata.html'
# write html
fig.write_html(fullfname)
print(f"Saved to {fullfname}")

Saved to /mnt/SpatialSequenceLearning/Simon/fr_stability/unit_fr_drift_Z_spikemetadata.html